name: Optimize resource pack
on: [push]
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
      - name: Download optimized pack
        uses: actions/download-artifact@v3
        with:
          name: Optimized pack
      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: action-v${{ github.run_number }}
          files: pack.zip
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: Srw5RQ6k
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 513425
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files-primary: pack.zip

          name: xali's Enhanced Vanilla v1.10.0
          version: v1.10.0
          version-type: release
          changelog-file: CHANGELOG.md

          game-versions: |
            1.19.2
            1.19.1
            1.19

          loaders: |
            fabric